### ISSUE TITLE
Bug when no optimization toolbox is installed

### ISSUE THREAD

**Issue by pag** [rodyo/FEX-minimize#1]
The block starting at line 229 of setoptimoptions.m reads

``` matlab
    if ~haveOptimToolbox
        for ii = 1:size(customOptions,1)
            options.(toolboxOptions{ii,1}) = toolboxOptions{ii,2}; end
    end
```

I think that should be `size(toolboxOptions)`, not `size(customOptions)`.

**Comment by rodyo** [comment]
You are correct; I corrected it in the latest push. Many thanks!
